[2024-07-08T02:01:07.008+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T02:01:07.025+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-07T22:15:00+00:00 [queued]>
[2024-07-08T02:01:07.029+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-07T22:15:00+00:00 [queued]>
[2024-07-08T02:01:07.029+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 3
[2024-07-08T02:01:07.035+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load> on 2024-07-07 22:15:00+00:00
[2024-07-08T02:01:07.041+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=62873) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-08T02:01:07.041+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Fail_Dags_Monitor', 'load', 'scheduled__2024-07-07T22:15:00+00:00', '--job-id', '1029', '--raw', '--subdir', 'DAGS_FOLDER/fail_dags_monitor.py', '--cfg-path', '/tmp/tmp1l2zfv1y']
[2024-07-08T02:01:07.042+0000] {standard_task_runner.py:63} INFO - Started process 62875 to run task
[2024-07-08T02:01:07.042+0000] {standard_task_runner.py:91} INFO - Job 1029: Subtask load
[2024-07-08T02:01:07.069+0000] {task_command.py:426} INFO - Running <TaskInstance: Fail_Dags_Monitor.load scheduled__2024-07-07T22:15:00+00:00 [running]> on host 0b64c9d791b9
[2024-07-08T02:01:07.116+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congminh.nguyen@onpoint.vn' AIRFLOW_CTX_DAG_ID='Fail_Dags_Monitor' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T22:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-07T22:15:00+00:00'
[2024-07-08T02:01:07.116+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T02:01:07.325+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/***/dags
[2024-07-08T02:29:27.089+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-07-08T02:29:27.097+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-08T02:29:27.103+0000] {process_utils.py:132} INFO - Sending 15 to group 62875. PIDs of all processes in the group: [62875]
[2024-07-08T02:29:27.104+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 62875
[2024-07-08T02:32:03.144+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=62875, name='airflow task ru', status='sleeping', started='02:01:06') did not respond to SIGTERM. Trying SIGKILL
[2024-07-08T02:32:03.150+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 62875
[2024-07-08T02:32:03.161+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=62875, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='02:01:06') (62875) terminated with exit code -9
[2024-07-08T02:32:03.162+0000] {standard_task_runner.py:178} ERROR - Job 1029 was killed before it finished (likely due to running out of memory)
